spring.application.name=backend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/mealmate
spring.datasource.username=postgres
spring.datasource.password=M0h@mmad.sh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true